//
//  LegacyProgressIDs.swift
//  ThaiSheet
//

import Foundation

/// Frozen snapshots of the identifiers shipped versions persisted, mapped to
/// the durable identifiers in use now (issue #29).
///
/// **These tables are data, not derivations.** They were generated once from
/// the v1.2 catalog and must never be regenerated from current content: their
/// whole purpose is that a key a user's device wrote in 2026 stays recognizable
/// after the sample word, written form, or transcription behind it is
/// corrected. Editing content is therefore free; this file does not change
/// with it.
///
/// **Coverage.** Every shipped release — v1.0-build4, v1.1-build5, v1.1-build6,
/// v1.1.1-build7, v1.2.0-build8 — derived identifiers from byte-identical
/// sources (`VowelCard.swift`, `ToneMarkCard.swift`, `ToneRuleCard.swift`,
/// `Cluster.swift`, `Vowel.swift`, `FlashcardItem.swift`) over byte-identical
/// `vowels.json`, `tone-marks.json`, and `clusters.json`. `tone-rules.json`
/// changed once, in v1.1.1, and that change only added `meaning` metadata — no
/// `full` value moved, so no key changed. One snapshot therefore covers every
/// historical key, including a device upgrading straight from v1.0 and legacy
/// keys arriving from an older iCloud client.
///
/// Consonants are absent because their keys never changed: already the glyph.
///
/// **Adding to them.** When a future release changes an identifier scheme
/// again, freeze that release's map as a second table and merge it in — never
/// rewrite these.
enum LegacyProgressIDs {

    /// Legacy → durable *progress* IDs for every release up to and including
    /// v1.2.0-build8: 72 vowel cards, 8 tone-mark cards, 98 tone-rule cards,
    /// 30 cluster cards.
    static let upToV1_2: [String: String] = [
        "cluster--ทร": "cluster-ทร:final",
        "cluster-กร-": "cluster-กร:initial",
        "cluster-กล-": "cluster-กล:initial",
        "cluster-กว-": "cluster-กว:initial",
        "cluster-ขร-": "cluster-ขร:initial",
        "cluster-ขล-": "cluster-ขล:initial",
        "cluster-ขว-": "cluster-ขว:initial",
        "cluster-คร-": "cluster-คร:initial",
        "cluster-คล-": "cluster-คล:initial",
        "cluster-คว-": "cluster-คว:initial",
        "cluster-จร-": "cluster-จร:initial",
        "cluster-ดร-": "cluster-ดร:initial",
        "cluster-ตร-": "cluster-ตร:initial",
        "cluster-ทร-": "cluster-ทร:initial",
        "cluster-บร-": "cluster-บร:initial",
        "cluster-บล-": "cluster-บล:initial",
        "cluster-ปร-": "cluster-ปร:initial",
        "cluster-ปล-": "cluster-ปล:initial",
        "cluster-ผล-": "cluster-ผล:initial",
        "cluster-พร-": "cluster-พร:initial",
        "cluster-พล-": "cluster-พล:initial",
        "cluster-สร-": "cluster-สร:initial",
        "cluster-หง-": "cluster-หง:initial",
        "cluster-หญ-": "cluster-หญ:initial",
        "cluster-หน-": "cluster-หน:initial",
        "cluster-หม-": "cluster-หม:initial",
        "cluster-หย-": "cluster-หย:initial",
        "cluster-หร-": "cluster-หร:initial",
        "cluster-หล-": "cluster-หล:initial",
        "cluster-หว-": "cluster-หว:initial",
        "toneMark-ก่า": "toneMark-่:Mid",
        "toneMark-ก้า": "toneMark-้:Mid",
        "toneMark-ก๊า": "toneMark-๊:Mid",
        "toneMark-ก๋า": "toneMark-๋:Mid",
        "toneMark-ข่า": "toneMark-่:High",
        "toneMark-ข้า": "toneMark-้:High",
        "toneMark-ค่า": "toneMark-่:Low",
        "toneMark-ค้า": "toneMark-้:Low",
        "toneRule-High-Any-Dead-ขัด": "toneRule-High-Any-Dead#s11",
        "toneRule-High-Any-Dead-ขับ": "toneRule-High-Any-Dead#s1",
        "toneRule-High-Any-Dead-ขาด": "toneRule-High-Any-Dead#s2",
        "toneRule-High-Any-Dead-ขุด": "toneRule-High-Any-Dead#s7",
        "toneRule-High-Any-Dead-ผัก": "toneRule-High-Any-Dead#s4",
        "toneRule-High-Any-Dead-ผิด": "toneRule-High-Any-Dead#s8",
        "toneRule-High-Any-Dead-สด": "toneRule-High-Any-Dead#s9",
        "toneRule-High-Any-Dead-สอบ": "toneRule-High-Any-Dead#s3",
        "toneRule-High-Any-Dead-สะอาด": "toneRule-High-Any-Dead#s14",
        "toneRule-High-Any-Dead-สัก": "toneRule-High-Any-Dead#s5",
        "toneRule-High-Any-Dead-สุก": "toneRule-High-Any-Dead#s13",
        "toneRule-High-Any-Dead-หก": "toneRule-High-Any-Dead#s6",
        "toneRule-High-Any-Dead-หัก": "toneRule-High-Any-Dead#s10",
        "toneRule-High-Any-Dead-เสร็จ": "toneRule-High-Any-Dead#s12",
        "toneRule-High-Any-Live-ขา": "toneRule-High-Any-Live#s1",
        "toneRule-High-Any-Live-ขาย": "toneRule-High-Any-Live#s13",
        "toneRule-High-Any-Live-ขาว": "toneRule-High-Any-Live#s2",
        "toneRule-High-Any-Live-ถาม": "toneRule-High-Any-Live#s7",
        "toneRule-High-Any-Live-ผม": "toneRule-High-Any-Live#s9",
        "toneRule-High-Any-Live-ฝน": "toneRule-High-Any-Live#s3",
        "toneRule-High-Any-Live-สวย": "toneRule-High-Any-Live#s14",
        "toneRule-High-Any-Live-สอง": "toneRule-High-Any-Live#s10",
        "toneRule-High-Any-Live-สาม": "toneRule-High-Any-Live#s11",
        "toneRule-High-Any-Live-สาย": "toneRule-High-Any-Live#s12",
        "toneRule-High-Any-Live-หนา": "toneRule-High-Any-Live#s6",
        "toneRule-High-Any-Live-หมี": "toneRule-High-Any-Live#s4",
        "toneRule-High-Any-Live-หา": "toneRule-High-Any-Live#s5",
        "toneRule-High-Any-Live-เขา": "toneRule-High-Any-Live#s8",
        "toneRule-High-Any-Live-ไหม": "toneRule-High-Any-Live#s15",
        "toneRule-Low-Any-Live-คน": "toneRule-Low-Any-Live#s5",
        "toneRule-Low-Any-Live-คาง": "toneRule-Low-Any-Live#s9",
        "toneRule-Low-Any-Live-งาม": "toneRule-Low-Any-Live#s11",
        "toneRule-Low-Any-Live-งู": "toneRule-Low-Any-Live#s13",
        "toneRule-Low-Any-Live-ทาง": "toneRule-Low-Any-Live#s6",
        "toneRule-Low-Any-Live-นม": "toneRule-Low-Any-Live#s10",
        "toneRule-Low-Any-Live-นา": "toneRule-Low-Any-Live#s2",
        "toneRule-Low-Any-Live-มา": "toneRule-Low-Any-Live#s1",
        "toneRule-Low-Any-Live-ยา": "toneRule-Low-Any-Live#s3",
        "toneRule-Low-Any-Live-ยาม": "toneRule-Low-Any-Live#s12",
        "toneRule-Low-Any-Live-ยาว": "toneRule-Low-Any-Live#s8",
        "toneRule-Low-Any-Live-รู": "toneRule-Low-Any-Live#s14",
        "toneRule-Low-Any-Live-ลม": "toneRule-Low-Any-Live#s4",
        "toneRule-Low-Any-Live-ลาน": "toneRule-Low-Any-Live#s7",
        "toneRule-Low-Long-Dead-ชอบ": "toneRule-Low-Long-Dead#s13",
        "toneRule-Low-Long-Dead-ชาติ": "toneRule-Low-Long-Dead#s14",
        "toneRule-Low-Long-Dead-ซาก": "toneRule-Low-Long-Dead#s9",
        "toneRule-Low-Long-Dead-ทอด": "toneRule-Low-Long-Dead#s7",
        "toneRule-Low-Long-Dead-นาก": "toneRule-Low-Long-Dead#s5",
        "toneRule-Low-Long-Dead-พลาด": "toneRule-Low-Long-Dead#s8",
        "toneRule-Low-Long-Dead-พูด": "toneRule-Low-Long-Dead#s3",
        "toneRule-Low-Long-Dead-มาก": "toneRule-Low-Long-Dead#s1",
        "toneRule-Low-Long-Dead-ยาก": "toneRule-Low-Long-Dead#s10",
        "toneRule-Low-Long-Dead-ราก": "toneRule-Low-Long-Dead#s6",
        "toneRule-Low-Long-Dead-ลาก": "toneRule-Low-Long-Dead#s2",
        "toneRule-Low-Long-Dead-ลูก": "toneRule-Low-Long-Dead#s4",
        "toneRule-Low-Long-Dead-เมือก": "toneRule-Low-Long-Dead#s12",
        "toneRule-Low-Long-Dead-โลก": "toneRule-Low-Long-Dead#s11",
        "toneRule-Low-Short-Dead/None-คะ": "toneRule-Low-Short-Dead/None#s1",
        "toneRule-Low-Short-Dead/None-ทะเล": "toneRule-Low-Short-Dead/None#s11",
        "toneRule-Low-Short-Dead/None-นะ": "toneRule-Low-Short-Dead/None#s2",
        "toneRule-Low-Short-Dead/None-พระ": "toneRule-Low-Short-Dead/None#s5",
        "toneRule-Low-Short-Dead/None-มะนาว": "toneRule-Low-Short-Dead/None#s9",
        "toneRule-Low-Short-Dead/None-มะพร้าว": "toneRule-Low-Short-Dead/None#s8",
        "toneRule-Low-Short-Dead/None-มะม่วง": "toneRule-Low-Short-Dead/None#s7",
        "toneRule-Low-Short-Dead/None-มะลิ": "toneRule-Low-Short-Dead/None#s6",
        "toneRule-Low-Short-Dead/None-มะเขือ": "toneRule-Low-Short-Dead/None#s10",
        "toneRule-Low-Short-Dead/None-ละ": "toneRule-Low-Short-Dead/None#s3",
        "toneRule-Low-Short-Dead/None-วัด": "toneRule-Low-Short-Dead/None#s4",
        "toneRule-Mid-Any-Dead-กด": "toneRule-Mid-Any-Dead#s5",
        "toneRule-Mid-Any-Dead-กัด": "toneRule-Mid-Any-Dead#s1",
        "toneRule-Mid-Any-Dead-กับ": "toneRule-Mid-Any-Dead#s11",
        "toneRule-Mid-Any-Dead-จบ": "toneRule-Mid-Any-Dead#s3",
        "toneRule-Mid-Any-Dead-จัก": "toneRule-Mid-Any-Dead#s10",
        "toneRule-Mid-Any-Dead-จุด": "toneRule-Mid-Any-Dead#s7",
        "toneRule-Mid-Any-Dead-ดัก": "toneRule-Mid-Any-Dead#s14",
        "toneRule-Mid-Any-Dead-ตก": "toneRule-Mid-Any-Dead#s8",
        "toneRule-Mid-Any-Dead-ตัด": "toneRule-Mid-Any-Dead#s4",
        "toneRule-Mid-Any-Dead-ตับ": "toneRule-Mid-Any-Dead#s12",
        "toneRule-Mid-Any-Dead-บท": "toneRule-Mid-Any-Dead#s9",
        "toneRule-Mid-Any-Dead-ปก": "toneRule-Mid-Any-Dead#s6",
        "toneRule-Mid-Any-Dead-ปะ": "toneRule-Mid-Any-Dead#s15",
        "toneRule-Mid-Any-Dead-ปิด": "toneRule-Mid-Any-Dead#s2",
        "toneRule-Mid-Any-Dead-เด็ก": "toneRule-Mid-Any-Dead#s13",
        "toneRule-Mid-Any-Live-กา": "toneRule-Mid-Any-Live#s1",
        "toneRule-Mid-Any-Live-กาง": "toneRule-Mid-Any-Live#s12",
        "toneRule-Mid-Any-Live-กิน": "toneRule-Mid-Any-Live#s7",
        "toneRule-Mid-Any-Live-จริง": "toneRule-Mid-Any-Live#s10",
        "toneRule-Mid-Any-Live-จาน": "toneRule-Mid-Any-Live#s6",
        "toneRule-Mid-Any-Live-ดาว": "toneRule-Mid-Any-Live#s8",
        "toneRule-Mid-Any-Live-ดิน": "toneRule-Mid-Any-Live#s11",
        "toneRule-Mid-Any-Live-ดี": "toneRule-Mid-Any-Live#s3",
        "toneRule-Mid-Any-Live-ตา": "toneRule-Mid-Any-Live#s2",
        "toneRule-Mid-Any-Live-ตาม": "toneRule-Mid-Any-Live#s9",
        "toneRule-Mid-Any-Live-บิน": "toneRule-Mid-Any-Live#s15",
        "toneRule-Mid-Any-Live-ปลา": "toneRule-Mid-Any-Live#s5",
        "toneRule-Mid-Any-Live-ออม": "toneRule-Mid-Any-Live#s13",
        "toneRule-Mid-Any-Live-เดิน": "toneRule-Mid-Any-Live#s14",
        "toneRule-Mid-Any-Live-ใจ": "toneRule-Mid-Any-Live#s4",
        "vowel-ก-": "vowel-o:Short:Closed",
        "vowel-กว-": "vowel-ua:Long:Closed",
        "vowel-กวย": "vowel-uay:Short:Closed",
        "vowel-กวาย": "vowel-uay:Long:Closed",
        "vowel-กอ": "vowel-aw:Long:Open",
        "vowel-กอ-": "vowel-aw:Long:Closed",
        "vowel-กอย": "vowel-awy:Long:Closed",
        "vowel-กะ": "vowel-a:Short:Open",
        "vowel-กั-": "vowel-a:Short:Closed",
        "vowel-กัย": "vowel-ai-ya:Short:Closed",
        "vowel-กัว": "vowel-ua:Long:Open",
        "vowel-กัวะ": "vowel-ua:Short:Open",
        "vowel-กา": "vowel-a:Long:Open",
        "vowel-กา-": "vowel-a:Long:Closed",
        "vowel-กาย": "vowel-aai:Long:Closed",
        "vowel-กาว": "vowel-ao:Long:Open",
        "vowel-กำ": "vowel-am:Short:Closed",
        "vowel-กิ": "vowel-i:Short:Open",
        "vowel-กิ-": "vowel-i:Short:Closed",
        "vowel-กิว": "vowel-iu:Short:Closed",
        "vowel-กี": "vowel-i:Long:Open",
        "vowel-กี-": "vowel-i:Long:Closed",
        "vowel-กึ": "vowel-ue:Short:Open",
        "vowel-กึ-": "vowel-ue:Short:Closed",
        "vowel-กื-": "vowel-ue:Long:Closed",
        "vowel-กือ": "vowel-ue:Long:Open",
        "vowel-กุ": "vowel-u:Short:Open",
        "vowel-กุ-": "vowel-u:Short:Closed",
        "vowel-กุย": "vowel-uy:Short:Closed",
        "vowel-กู": "vowel-u:Long:Open",
        "vowel-กู-": "vowel-u:Long:Closed",
        "vowel-ก็อ-": "vowel-aw:Short:Closed",
        "vowel-ก็อย": "vowel-awy:Short:Closed",
        "vowel-ฤ": "vowel-rue:Short:Open",
        "vowel-ฤ-": "vowel-ri:Short:Closed",
        "vowel-ฤๅ": "vowel-rue:Long:Open",
        "vowel-ฦ": "vowel-lue:Short:Open",
        "vowel-ฦๅ": "vowel-lue:Long:Open",
        "vowel-เก": "vowel-e:Long:Open",
        "vowel-เก-": "vowel-e:Long:Closed",
        "vowel-เกย": "vowel-oey:Long:Closed",
        "vowel-เกว": "vowel-eo:Long:Open",
        "vowel-เกอ": "vowel-oe:Long:Open",
        "vowel-เกอว": "vowel-oew:Long:Closed",
        "vowel-เกอะ": "vowel-oe:Short:Open",
        "vowel-เกะ": "vowel-e:Short:Open",
        "vowel-เกา": "vowel-ao:Short:Closed",
        "vowel-เกาะ": "vowel-aw:Short:Open",
        "vowel-เกิ-": "vowel-oe:Short:Closed",
        "vowel-เกีย": "vowel-ia:Long:Open",
        "vowel-เกีย-": "vowel-ia:Long:Closed",
        "vowel-เกียว": "vowel-iao:Long:Closed",
        "vowel-เกียะ": "vowel-ia:Short:Open",
        "vowel-เกือ": "vowel-uea:Long:Open",
        "vowel-เกือ-": "vowel-uea:Long:Closed",
        "vowel-เกือย": "vowel-ueay:Long:Closed",
        "vowel-เกือะ": "vowel-uea:Short:Open",
        "vowel-เก็-": "vowel-e:Short:Closed",
        "vowel-เก็ว": "vowel-eo:Short:Closed",
        "vowel-แก": "vowel-ae:Long:Open",
        "vowel-แก-": "vowel-ae:Long:Closed",
        "vowel-แกว": "vowel-aeo:Long:Open",
        "vowel-แกะ": "vowel-ae:Short:Open",
        "vowel-แก็-": "vowel-ae:Short:Closed",
        "vowel-แก็ว": "vowel-aeo:Short:Closed",
        "vowel-โก": "vowel-o:Long:Open",
        "vowel-โก-": "vowel-o:Long:Closed",
        "vowel-โกย": "vowel-oy:Long:Closed",
        "vowel-โกะ": "vowel-o:Short:Open",
        "vowel-ใก": "vowel-ai-mai-muan:Short:Open",
        "vowel-ไก": "vowel-ai-mai-malai:Short:Open",
        "vowel-ไกย": "vowel-ai-mai-malai-ya:Short:Closed",
    ]

    /// Legacy → durable *voice-override* IDs (`fc_voiceOverrides`), which key on
    /// a row's identity rather than a card's: 33 vowel rows and 30 clusters.
    /// Tone-mark and tone-rule overrides are absent because they key on the
    /// class-entry sound key and the rule id, neither of which changed.
    static let voiceOverridesUpToV1_2: [String: String] = [
        "cluster--ทร": "cluster-ทร:final",
        "cluster-กร-": "cluster-กร:initial",
        "cluster-กล-": "cluster-กล:initial",
        "cluster-กว-": "cluster-กว:initial",
        "cluster-ขร-": "cluster-ขร:initial",
        "cluster-ขล-": "cluster-ขล:initial",
        "cluster-ขว-": "cluster-ขว:initial",
        "cluster-คร-": "cluster-คร:initial",
        "cluster-คล-": "cluster-คล:initial",
        "cluster-คว-": "cluster-คว:initial",
        "cluster-จร-": "cluster-จร:initial",
        "cluster-ดร-": "cluster-ดร:initial",
        "cluster-ตร-": "cluster-ตร:initial",
        "cluster-ทร-": "cluster-ทร:initial",
        "cluster-บร-": "cluster-บร:initial",
        "cluster-บล-": "cluster-บล:initial",
        "cluster-ปร-": "cluster-ปร:initial",
        "cluster-ปล-": "cluster-ปล:initial",
        "cluster-ผล-": "cluster-ผล:initial",
        "cluster-พร-": "cluster-พร:initial",
        "cluster-พล-": "cluster-พล:initial",
        "cluster-สร-": "cluster-สร:initial",
        "cluster-หง-": "cluster-หง:initial",
        "cluster-หญ-": "cluster-หญ:initial",
        "cluster-หน-": "cluster-หน:initial",
        "cluster-หม-": "cluster-หม:initial",
        "cluster-หย-": "cluster-หย:initial",
        "cluster-หร-": "cluster-หร:initial",
        "cluster-หล-": "cluster-หล:initial",
        "cluster-หว-": "cluster-หว:initial",
        "vowel-aa/ah-กั-|กะ|กา-|กา": "vowel-a",
        "vowel-aai-กาย": "vowel-aai",
        "vowel-aaw-ก็อ-|เกาะ|กอ-|กอ": "vowel-aw",
        "vowel-aawy-ก็อย|กอย": "vowel-awy",
        "vowel-ae-แก็-|แกะ|แก-|แก": "vowel-ae",
        "vowel-aeo-แก็ว|แกว": "vowel-aeo",
        "vowel-ahm-กำ": "vowel-am",
        "vowel-ai-กัย": "vowel-ai-ya",
        "vowel-ai-ใก": "vowel-ai-mai-muan",
        "vowel-ai-ไก": "vowel-ai-mai-malai",
        "vowel-ai-ไกย": "vowel-ai-mai-malai-ya",
        "vowel-ao-เกา|กาว": "vowel-ao",
        "vowel-ayo-เก็ว|เกว": "vowel-eo",
        "vowel-ee-กิ-|กิ|กี-|กี": "vowel-i",
        "vowel-eeuy-เกย": "vowel-oey",
        "vowel-eh/ey-เก็-|เกะ|เก-|เก": "vowel-e",
        "vowel-erh/uuhr-เกิ-|เกอะ|เกิ-|เกอ": "vowel-oe",
        "vowel-eu-กึ-|กึ|กื-|กือ": "vowel-ue",
        "vowel-eua-เกือะ|เกือ-|เกือ": "vowel-uea",
        "vowel-euuay-เกือย": "vowel-ueay",
        "vowel-ia-เกียะ|เกีย-|เกีย": "vowel-ia",
        "vowel-iaao-เกียว": "vowel-iao",
        "vowel-iu-กิว": "vowel-iu",
        "vowel-lue-ฦ|ฦๅ": "vowel-lue",
        "vowel-oh-ก-|โกะ|โก-|โก": "vowel-o",
        "vowel-oo-กุ-|กุ|กู-|กู": "vowel-u",
        "vowel-oy/ohy-โกย": "vowel-oy",
        "vowel-ri-ฤ-": "vowel-ri",
        "vowel-rue-ฤ|ฤๅ": "vowel-rue",
        "vowel-ua-กัวะ|กว-|กัว": "vowel-ua",
        "vowel-uaaw-เกอว": "vowel-oew",
        "vowel-uay-กวย|กวาย": "vowel-uay",
        "vowel-uy-กุย": "vowel-uy",
    ]
}
