//
//  SettingsView.swift
//  ThaiSheet
//

import SwiftUI

/// App-wide settings sheet, reachable from both tabs
struct SettingsView: View {
    @Bindable var settings: FlashcardSettings
    var syncedStore: SyncedKeyValueStore?
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        // The live device voice is offered only when a Thai system voice is installed
        // (or if it's already selected, so the picker selection isn't orphaned).
        let availableVoices = RecordedVoice.recordedCases
            + ((AudioPlayer.isThaiVoiceAvailable || settings.recordedVoice == .device) ? [.device] : [])

        NavigationStack {
            Form {
                Section {
                    strategyOption(
                        title: "Wanikani-style SRS",
                        description: "Prioritizes cards due for review based on your progress. Uses spaced repetition to optimize learning.",
                        isSelected: settings.useIntelligentSelection
                    ) {
                        settings.useIntelligentSelection = true
                    }

                    strategyOption(
                        title: "Sequential",
                        description: "Shows cards in fixed order. Good for systematic review of all cards.",
                        isSelected: !settings.useIntelligentSelection
                    ) {
                        settings.useIntelligentSelection = false
                    }
                } header: {
                    Text("Flashcards: Learning Strategy")
                }

                Section {
                    Toggle("Sync across devices", isOn: $settings.iCloudSyncEnabled)
                    if settings.iCloudSyncEnabled, let syncedStore {
                        HStack {
                            Text("Last synced")
                            Spacer()
                            if let date = syncedStore.lastSyncDate {
                                Text(date, style: .relative)
                                    .foregroundColor(.secondary)
                            } else {
                                Text("Never")
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                } header: {
                    Text("iCloud Sync")
                }

                // The pronunciation-voice picker ships; the language override stays dev-only.
                Section {
                    Picker("Voice", selection: $settings.recordedVoice) {
                        ForEach(availableVoices) { voice in
                            Text(voice.displayName).tag(voice)
                        }
                    }
                    .pickerStyle(.inline)
                    .labelsHidden()

                    NavigationLink {
                        VoiceOverridesView()
                    } label: {
                        HStack {
                            Text("Item voice overrides", bundle: .appLanguage)
                            Spacer()
                            Text("\(settings.overriddenItemIDs.count)")
                                .foregroundStyle(.secondary)
                        }
                    }
                } header: {
                    Text("Pronunciation voice")
                } footer: {
                    Text("Recorded voices are generated by Google Cloud TTS and ElevenLabs; the device voice uses the Apple system voice.")
                }

                #if DEBUG
                Section {
                    Picker(selection: $settings.appLanguage) {
                        ForEach(FlashcardSettings.supportedLanguages, id: \.code) { lang in
                            Text(lang.name).tag(lang.code)
                        }
                    } label: {
                        Text("Language")
                    }
                } header: {
                    Text("Language")
                }
                #endif

                Section {
                    NavigationLink {
                        AboutView()
                    } label: {
                        Text("About")
                    }
                }
            }
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
        }
    }


    @ViewBuilder
    private func strategyOption(
        title: LocalizedStringKey,
        description: LocalizedStringKey,
        isSelected: Bool,
        action: @escaping () -> Void
    ) -> some View {
        Button(action: action) {
            HStack(alignment: .top, spacing: 12) {
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .foregroundColor(isSelected ? .accentColor : .secondary)
                    .font(.title2)

                VStack(alignment: .leading, spacing: 4) {
                    Text(title)
                        .font(.body.weight(.medium))
                        .foregroundColor(.primary)

                    Text(description)
                        .font(.caption)
                        .foregroundColor(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                Spacer()
            }
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }
}

#Preview {
    SettingsView(settings: FlashcardSettings())
}
