//
//  SettingsView.swift
//  ThaiSheet
//

import SwiftUI

/// App-wide settings sheet, reachable from both tabs
struct SettingsView: View {
    @Bindable var settings: FlashcardSettings
    var syncedStore: SyncedKeyValueStore?
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        #if DEBUG
        let isThaiVoiceAvailable = AudioPlayer.isThaiVoiceAvailable
        // In DEBUG the recorded/device source is selectable, so only show the voice-set
        // picker when the recorded source is active. Release always uses recorded audio.
        let showsRecordedVoicePicker = settings.audioSource == .recorded
        #else
        let showsRecordedVoicePicker = true
        #endif

        NavigationStack {
            Form {
                Section {
                    strategyOption(
                        title: "Wanikani-style SRS",
                        description: "Prioritizes cards due for review based on your progress. Uses spaced repetition to optimize learning.",
                        isSelected: settings.useIntelligentSelection
                    ) {
                        settings.useIntelligentSelection = true
                    }

                    strategyOption(
                        title: "Sequential",
                        description: "Shows cards in fixed order. Good for systematic review of all cards.",
                        isSelected: !settings.useIntelligentSelection
                    ) {
                        settings.useIntelligentSelection = false
                    }
                } header: {
                    Text("Flashcards: Learning Strategy")
                }

                Section {
                    Toggle("Sync across devices", isOn: $settings.iCloudSyncEnabled)
                    if settings.iCloudSyncEnabled, let syncedStore {
                        HStack {
                            Text("Last synced")
                            Spacer()
                            if let date = syncedStore.lastSyncDate {
                                Text(date, style: .relative)
                                    .foregroundColor(.secondary)
                            } else {
                                Text("Never")
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                } header: {
                    Text("iCloud Sync")
                }

                // The recorded-voice picker ships; the recorded/device source toggle and
                // language override remain dev-only tools.
                if showsRecordedVoicePicker {
                    Section {
                        Picker("Voice", selection: $settings.recordedVoice) {
                            ForEach(RecordedVoice.allCases) { voice in
                                Text(voice.displayName).tag(voice)
                            }
                        }
                        .pickerStyle(.inline)
                        .labelsHidden()
                    } header: {
                        Text("Pronunciation voice")
                    } footer: {
                        Text("Audio is generated by Google Cloud TTS and ElevenLabs.")
                    }
                }

                #if DEBUG
                Section {
                    Picker(
                        "Audio source",
                        selection: availableAudioSourceBinding(isThaiVoiceAvailable: isThaiVoiceAvailable)
                    ) {
                        Text("Recorded voice").tag(AudioSource.recorded)
                        Text("Device voice")
                            .tag(AudioSource.device)
                            .disabled(!isThaiVoiceAvailable)
                    }
                    .pickerStyle(.inline)
                    .labelsHidden()
                } header: {
                    Text("Audio source (dev)")
                } footer: {
                    if !isThaiVoiceAvailable {
                        Text("A Thai device voice is not available on this device.")
                    }
                }

                Section {
                    Picker(selection: $settings.appLanguage) {
                        ForEach(FlashcardSettings.supportedLanguages, id: \.code) { lang in
                            Text(lang.name).tag(lang.code)
                        }
                    } label: {
                        Text("Language")
                    }
                } header: {
                    Text("Language")
                }
                #endif

                Section {
                    NavigationLink {
                        AboutView()
                    } label: {
                        Text("About")
                    }
                }
            }
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
        }
    }

    #if DEBUG
    private func availableAudioSourceBinding(isThaiVoiceAvailable: Bool) -> Binding<AudioSource> {
        Binding {
            AudioPlayer.resolvedAudioSource(
                settings.audioSource,
                isThaiVoiceAvailable: isThaiVoiceAvailable
            )
        } set: { source in
            guard AudioPlayer.resolvedAudioSource(
                source,
                isThaiVoiceAvailable: isThaiVoiceAvailable
            ) == source else { return }
            settings.audioSource = source
        }
    }
    #endif

    @ViewBuilder
    private func strategyOption(
        title: LocalizedStringKey,
        description: LocalizedStringKey,
        isSelected: Bool,
        action: @escaping () -> Void
    ) -> some View {
        Button(action: action) {
            HStack(alignment: .top, spacing: 12) {
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .foregroundColor(isSelected ? .accentColor : .secondary)
                    .font(.title2)

                VStack(alignment: .leading, spacing: 4) {
                    Text(title)
                        .font(.body.weight(.medium))
                        .foregroundColor(.primary)

                    Text(description)
                        .font(.caption)
                        .foregroundColor(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                Spacer()
            }
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }
}

#Preview {
    SettingsView(settings: FlashcardSettings())
}
